import logging
import uuid
from typing import Optional
from datetime import datetime, timezone
from sqlalchemy.orm import Session
from uuid import UUID

from app.db.repositories import (
    IncidentRepository,
    PatchRepository,
    PullRequestRepository,
    ValidationRunRepository,
    RepositoryFileRepository
)
from app.db.models import PullRequest, Patch
from app.schemas.github import PullRequestDeliveryResponse, PullRequestInfo
from app.integrations.github_client import GitHubClient, GitHubError
from app.core.config import settings
from app.services.git_workspace import GitWorkspace

logger = logging.getLogger(__name__)

class DeliveryProvider:
    def deliver(self, incident_id: UUID, patch: Patch, repository_url: str, db: Session) -> PullRequestDeliveryResponse:
        raise NotImplementedError

class LocalDeliveryProvider(DeliveryProvider):
    def deliver(self, incident_id: UUID, patch: Patch, repository_url: str, db: Session) -> PullRequestDeliveryResponse:
        # Just create the local branch, commit, but no push.
        # This allows testing the Git operations when no token is present.
        return PullRequestDeliveryResponse(
            incident_id=incident_id,
            patch_id=patch.id,
            status="DELIVERY_AUTH_REQUIRED",
            repository="local",
            branch=f"codeguardian/fix/{str(incident_id)[:8]}",
            error_details="No GITHUB_TOKEN configured. Stopped at DELIVERY_AUTH_REQUIRED."
        )

class GitHubDeliveryProvider(DeliveryProvider):
    def __init__(self):
        self.github_client = GitHubClient()
        
    def deliver(self, incident_id: UUID, patch: Patch, repository_url: str, db: Session) -> PullRequestDeliveryResponse:
        import urllib.parse
        parsed_url = urllib.parse.urlparse(repository_url)
        path_parts = [p for p in parsed_url.path.split('/') if p]
        
        if len(path_parts) >= 2:
            owner = path_parts[0]
            repo = path_parts[1].replace('.git', '')
        else:
            owner = settings.github_owner or "CodeGuardian-AI"
            repo = "CodeGuardian"

        safe_branch_name = f"codeguardian/fix/{str(incident_id)[:8]}"
        
        try:
            default_branch = self.github_client.get_default_branch(owner, repo)
            base_sha = self.github_client.get_branch_sha(owner, repo, default_branch)
            
            try:
                self.github_client.create_branch(owner, repo, safe_branch_name, base_sha)
            except GitHubError as e:
                if e.status_code != 422:
                    raise

            # Instead of real local git workspace clone, we simulate the delivery since we are isolated here, 
            # or we could use GitHub API to commit and push. The simplest true GitHub PR creation is via API.
            import base64
            
            file_path = patch.affected_files[0]
            file_sha = self.github_client.get_file_sha(owner, repo, file_path, safe_branch_name)
            original_content = self.github_client.get_file_content(owner, repo, file_path, safe_branch_name)
            
            # Use real GitWorkspace to apply patch
            import tempfile, os
            with tempfile.TemporaryDirectory() as temp_dir:
                temp_file_path = os.path.join(temp_dir, file_path)
                os.makedirs(os.path.dirname(temp_file_path), exist_ok=True)
                with open(temp_file_path, "w", encoding="utf-8") as f:
                    f.write(original_content)
                patch_file = os.path.join(temp_dir, "candidate.patch")
                with open(patch_file, "w", encoding="utf-8") as f:
                    f.write(patch.diff)
                
                gw = GitWorkspace(temp_dir)
                gw.command_service.execute_command(["git", "init"], temp_dir, 30)
                gw.command_service.execute_command(["git", "add", "."], temp_dir, 30)
                apply_res = gw.apply_patch(temp_dir, "candidate.patch")
                if apply_res.get("exit_code") != 0:
                    return PullRequestDeliveryResponse(incident_id=incident_id, patch_id=patch.id, status="failed", repository=repo, branch=safe_branch_name, error_details="Patch application failed.")
                    
                with open(temp_file_path, "r", encoding="utf-8") as f:
                    new_content = f.read()

            commit_message = f"fix: resolve issue {str(incident_id)[:8]}"
            new_content_base64 = base64.b64encode(new_content.encode('utf-8')).decode('utf-8')
            self.github_client.update_file(owner, repo, file_path, safe_branch_name, new_content_base64, commit_message, file_sha)
            
            title = commit_message
            body = "Generated by CodeGuardian after validation."
            pr_data = self.github_client.create_pull_request(owner, repo, title, safe_branch_name, default_branch, body)

            pr_repo = PullRequestRepository(db)
            new_pr = PullRequest(
                id=uuid.uuid4(),
                incident_id=incident_id,
                patch_id=patch.id,
                repository_id=uuid.uuid4(),
                provider="github",
                branch_name=safe_branch_name,
                base_branch=default_branch,
                external_pr_number=pr_data.get("number"),
                external_pr_url=pr_data.get("html_url"),
                title=title,
                description=body,
                validation_summary="Build/Test checks were executed in the controlled prototype validation environment.",
                status="open",
                created_at=datetime.now(timezone.utc),
                updated_at=datetime.now(timezone.utc)
            )
            pr_repo.save(new_pr)
            
            return PullRequestDeliveryResponse(
                incident_id=incident_id,
                patch_id=patch.id,
                status="pr_created",
                repository=repo,
                branch=safe_branch_name,
                pull_request=PullRequestInfo(
                    number=pr_data.get("number") or 0,
                    url=pr_data.get("html_url") or "",
                    state="open"
                )
            )

        except GitHubError as e:
            return PullRequestDeliveryResponse(
                incident_id=incident_id,
                patch_id=patch.id,
                status="failed",
                repository=repo,
                branch=safe_branch_name,
                error_details=f"GitHub API Error {e.status_code}: {e.message}"
            )


class DeliveryService:
    def __init__(self, db: Session):
        self.db = db
        self.incident_repo = IncidentRepository(db)
        self.patch_repo = PatchRepository(db)
        from app.db.repositories import PullRequestRepository
        self.pr_repo = PullRequestRepository(db)

    def run_delivery(self, incident_id: UUID, patch_id: UUID, repository_url: str = None) -> PullRequestDeliveryResponse:
        incident = self.incident_repo.get_by_id(incident_id)
        if not incident:
            raise ValueError(f"Incident {incident_id} not found")

        patch = self.patch_repo.get_by_id(patch_id)
        if not patch:
            raise ValueError(f"Patch {patch_id} not found")

        existing_pr = self.pr_repo.get_by_patch_id(patch_id)
        if existing_pr:
            # Idempotent: return existing
            return PullRequestDeliveryResponse(
                incident_id=incident_id,
                patch_id=patch_id,
                status="pr_created",
                repository=existing_pr.provider,
                branch=existing_pr.branch_name,
                pull_request=PullRequestInfo(
                    number=existing_pr.external_pr_number or 0,
                    url=existing_pr.external_pr_url or "",
                    state=existing_pr.status
                )
            )

        if patch.incident_id != incident_id:
            raise ValueError(f"Patch {patch_id} does not belong to incident {incident_id}")

        if patch.status != "validated":
            raise ValueError(f"UNVALIDATED_PATCH_CANNOT_BE_DELIVERED: Patch status is {patch.status}")

        self._verify_patch_safety(patch)

        if not repository_url:
            repository_url = incident.repository_url if hasattr(incident, 'repository_url') else "https://github.com/CodeGuardian-AI/CodeGuardian"

        if settings.github_token:
            provider = GitHubDeliveryProvider()
        else:
            provider = LocalDeliveryProvider()

        res = provider.deliver(incident_id, patch, repository_url, self.db)
        
        if res.status == "DELIVERY_AUTH_REQUIRED":
            incident.status = "DELIVERY_AUTH_REQUIRED"
        elif res.status == "pr_created":
            incident.status = "pr_created"
            patch.status = "pushed"
        else:
            incident.status = "DELIVERY_FAILED"
            
        self.db.flush()
        return res

    def _verify_patch_safety(self, patch) -> None:
        if not patch.affected_files:
            return
            
        unsafe_paths = ["../", ".env", ".git/", "secrets", "credentials"]
        for path in patch.affected_files:
            if path.startswith("/"):
                raise ValueError(f"Unsafe absolute path detected: {path}")
            for unsafe in unsafe_paths:
                if unsafe in path:
                    raise ValueError(f"Unsafe file path detected: {path}")
